Repository Flickit-Platform-Dev/flickit-assessment, pull requests merged in 2024-07, with the labels that each got.

#26 FAC-386 Rename account_user table to fau_user
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/user/UserJpaEntity.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.23.xml
Labels: Ready to Merge

#30 FAC-390 Impl load user service
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/user/GetUserProfileResponseDto.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/user/GetUserProfileRestController.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/out/persistence/user/UserMapper.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/out/persistence/user/UserPersistenceJpaAdapter.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/domain/User.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/user/GetUserProfileUseCase.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/out/user/LoadUserPort.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/user/GetUserProfileService.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/port/in/user/GetUserProfileUseCaseParamTest.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/user/GetUserProfileServiceTest.java
  flickit-assessment-users/src/test/resources/postman/flickit-assessment-users.postman_collection.json
Labels: Ready to Merge

#35 FAC-395 Impl create user service
  flickit-assessment-common/src/main/resources/i18n/users/messages_en.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/user/UserJpaEntity.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/user/CreateUserRequestDto.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/user/CreateUserResponseDto.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/user/CreateUserRestController.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/out/persistence/user/UserMapper.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/out/persistence/user/UserPersistenceJpaAdapter.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/user/CreateUserUseCase.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/out/user/CreateUserPort.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/user/CreateUserService.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/common/ErrorMessageKey.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/port/in/user/CreateUserUseCaseParamTest.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/user/CreateUserServiceTest.java
  flickit-assessment-users/src/test/resources/postman/flickit-assessment-users.postman_collection.json
Labels: Ready to Review

#40 FAC-403 Impl users me service
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/user/GetUsersMeResponseDto.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/user/GetUsersMeRestController.java
  flickit-assessment-users/src/test/resources/postman/flickit-assessment-users.postman_collection.json
Labels: Ready to Review

#121 FAC-487: feat: Add manageable and viewable to the result of GetAssessmentService
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/GetAssessmentResponseDto.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/GetAssessmentRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/GetAssessmentUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentServiceTest.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
Labels: Ready to Review

#128 FAC-500 Impl load user service
  flickit-assessment-common/src/main/resources/i18n/users/messages_en.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/user/UserJpaRepository.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/user/GetUserByEmailResponseDto.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/user/GetUserByEmailRestController.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/out/persistence/user/UserPersistenceJpaAdapter.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/user/GetUserByEmailUseCase.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/out/user/LoadUserPort.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/user/GetUserByEmailService.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/common/ErrorMessageKey.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/port/in/user/GetUserByEmailUseCaseParamTest.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/user/GetUserByEmailServiceTest.java
  flickit-assessment-users/src/test/resources/postman/flickit-assessment-users.postman_collection.json
Labels: In Progress

#108 FAC-476: Add evidence attachment
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/FileProperties.java
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/evidenceattachment/AddEvidenceAttachmentRequestDto.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/evidenceattachment/AddEvidenceAttachmentResponseDto.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/evidenceattachment/AddEvidenceAttachmentRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/minio/MinioAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/evidenceattachment/EvidenceAttachmentMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/evidenceattachment/EvidenceAttachmentPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/EvidenceAttachment.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/evidenceattachment/AddEvidenceAttachmentUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/evidenceattachment/CountEvidenceAttachmentsPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/evidenceattachment/CreateEvidenceAttachmentPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/evidenceattachment/UploadEvidenceAttachmentPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/evidenceattachment/AddEvidenceAttachmentService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/evidenceattachment/AddEvidenceAttachmentUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/evidenceattachment/AddEvidenceAttachmentServiceTest.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/config/MinioBucketInitializer.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/config/MinioConfigProperties.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidence/EvidenceJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidenceattachment/EvidenceAttachmentJpaRepository.java
  flickit-assessment-server/src/main/resources/application-dev.properties
Labels: Ready to Review

#118 FAC-483: Get evidence attachments
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/evidenceattachment/GetEvidenceAttachmentsResponseDto.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/evidenceattachment/GetEvidenceAttachmentsRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/evidenceattachment/EvidenceAttachmentMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/evidenceattachment/EvidenceAttachmentPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/evidenceattachment/GetEvidenceAttachmentsUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/evidenceattachment/LoadEvidenceAttachmentsPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/evidenceattachment/GetEvidenceAttachmentsService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/evidenceattachment/GetEvidenceAttachmentsUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/evidenceattachment/GetEvidenceAttachmentsServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/EvidenceMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/UserMother.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidenceattachment/EvidenceAttachmentJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidenceattachment/EvidenceAttachmentWithUserView.java
Labels: Ready to Review

#131 FAC-503: fix: Use FileNameUtils for extracting file extension
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/FileProperties.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/update/UpdateKitByDslService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/kitdsl/UploadKitDslService.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/kitdsl/UploadKitDSLServiceTest.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/out/minio/MinioAdapter.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/expertgroup/CreateExpertGroupService.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/expertgroup/UpdateExpertGroupPictureService.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/expertgroup/CreateExpertGroupServiceTest.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/expertgroup/UpdateExpertGroupPictureServiceTest.java
Labels: Ready to Review

#142 FAC-506:fix:Fix calclulate attribute score bug
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/questionimpact/QuestionImpactMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/Answer.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AttributeValue.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/QuestionImpact.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/AnswerOptionImpactTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/AnswerTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/AttributeValueTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/QuestionTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AnswerMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AnswerOptionImpactMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AnswerOptionMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AttributeMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AttributeValueMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/QuestionImpactMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/QuestionMother.java
Labels: Ready to Review

#141 FAC-515: Create assessment invitee table
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentinvitee/AssessmentInviteeJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentinvitee/AssessmentInviteeJpaRepository.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.25.xml
Labels: Ready to Review

#143 FAC-516:featureAdd user to space in grant user assessment role service
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/SpaceAccessChecker.java
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentuserrole/AssessmentUserRolePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/spaceuseraccess/SpaceUserAccessMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/spaceuseraccess/SpaceUserAccessPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessment/CheckAssessmentSpaceMembershipPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessment/CheckUserAssessmentAccessPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentuserrole/LoadUserRoleForAssessmentPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/spaceuseraccess/CreateAssessmentSpaceUserAccessPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/ReportAssessmentService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentuserrole/AssessmentAccessCheckerService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentuserrole/AssessmentPermissionCheckerService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentuserrole/DeleteUserAssessmentRoleService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentuserrole/GrantUserAssessmentRoleService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentuserrole/UpdateUserAssessmentRoleService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/ReportAssessmentServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentuserrole/AssessmentAccessCheckerServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentuserrole/AssessmentPermissionCheckerServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentuserrole/DeleteUserAssessmentRoleServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentuserrole/GrantUserAssessmentRoleServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentuserrole/UpdateUserAssessmentRoleServiceTest.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessment/AssessmentJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentuserrole/AssessmentUserRoleIdView.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentuserrole/AssessmentUserRoleJpaRepository.java
Labels: Ready to Review

#148 FAC-519:feature:Impl get assessment invitee list service
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentinvitee/GetAssessmentInviteeListRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentinvitee/AssessmentInviteeMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentinvitee/AssessmentInviteePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentInvitee.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentinvitee/GetAssessmentInviteeListUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentinvitee/LoadAssessmentInviteeListPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentinvitee/GetAssessmentInviteeListService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentuserrole/GetAssessmentUsersService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessmentinvitee/GetAssessmentInviteeListUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentinvitee/GetAssessmentInviteeListServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentuserrole/GetAssessmentUsersServiceTest.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentinvitee/AssessmentInviteeJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentinvitee/AssessmentInviteeJpaRepository.java
Labels: Ready to Review

#129 FAC-497: Add title and createdBy uniqueness constraint
  flickit-assessment-common/src/main/resources/i18n/users/messages_en.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/space/SpaceJpaRepository.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.25.xml
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/out/persistence/constraint/AssessmentUsersDataConstraintErrorMapper.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/out/persistence/space/SpacePersistenceJpaAdapter.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/domain/Space.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/space/CreateSpaceUseCase.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/space/UpdateSpaceUseCase.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/out/space/UpdateSpacePort.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/space/CreateSpaceService.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/space/UpdateSpaceService.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/common/ErrorMessageKey.java
Labels: Ready to Review

#125 FAC-475 Impl evidence attachments deletion service
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/evidenceattachment/DeleteEvidenceAttachmentRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/minio/MinioAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/evidenceattachment/EvidenceAttachmentPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/evidenceattachment/DeleteEvidenceAttachmentUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/evidenceattachment/DeleteEvidenceAttachmentPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/evidenceattachment/LoadEvidenceAttachmentFilePathPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/minio/DeleteEvidenceAttachmentFilePort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/evidenceattachment/DeleteEvidenceAttachmentService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/evidenceattachment/DeleteEvidenceAttachmentUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/evidenceattachment/DeleteEvidenceAttachmentServiceTest.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
Labels: Ready to Review

#151 FAC-523: Create accept assessment invitations service
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentinvitee/AcceptAssessmentInvitationsRequestDto.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentinvitee/AcceptAssessmentInvitationsRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentinvitee/AssessmentInviteeMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentinvitee/AssessmentInviteePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentuserrole/AssessmentUserRoleMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentuserrole/AssessmentUserRolePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/user/UserPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentInvitee.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRoleItem.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentinvitee/AcceptAssessmentInvitationsUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentinvitee/DeleteAssessmentUserInvitationPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentinvitee/LoadAssessmentsUserInvitationsPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentuserrole/GrantUserAssessmentRolePort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/user/LoadUserEmailByUserIdPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentinvitee/AcceptAssessmentInvitationsService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentinvitee/InviteAssessmentUserService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessmentinvitee/AcceptAssessmentInvitationsUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentinvitee/AcceptAssessmentInvitationsServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentinvitee/GetAssessmentInviteeListServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentInviteeMother.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentinvitee/AssessmentInviteeJpaRepository.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/spaceinvitee/AcceptSpaceInvitationsRestController.java
Labels: Ready to Review

#150 FAC-524 Impl get current user permission list service
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentuserrole/GetAssessmentUserPermissionsRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentuserrole/GetAssessmentUserPermissionsUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetSpaceAssessmentListService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/ReportAssessmentService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentuserrole/GetAssessmentUserPermissionsService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessmentuserrole/GetAssessmentUserPermissionsUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetSpaceAssessmentListServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/ReportAssessmentServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentuserrole/GetAssessmentUserPermissionsServiceTest.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
Labels: Ready to Review

#139 FAC-509: feat: Add attachmentsCount to the result of evidenceList
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/evidence/EvidenceMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/evidence/EvidencePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/evidence/GetEvidenceListUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/evidence/GetEvidenceListService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/evidence/GetEvidenceListServiceTest.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidence/EvidenceJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidence/EvidenceJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidence/EvidenceWithAttachmentsCountView.java
Labels: Ready to Merge

#138 FAC-513: Add attachments count to attribute evidence list
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/evidence/EvidencePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/evidence/GetAttributeEvidenceListUseCase.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/evidence/GetAttributeEvidenceListServiceTest.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidence/EvidenceJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidence/MinimalEvidenceView.java
Labels: Ready to Review

#123 FAC-490: ImplGetEvidence Service
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/evidence/GetEvidenceResponseDto.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/evidence/GetEvidenceRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answeroption/AnswerOptionMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/answeroption/AnswerOptionMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/answeroption/AnswerOptionPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/question/QuestionMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/question/QuestionPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/questionnaire/QuestionnaireMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/questionnaire/QuestionnairePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/Question.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/Questionnaire.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/evidence/GetEvidenceUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/answeroption/LoadAnswerOptionsByQuestionPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/question/LoadQuestionPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/evidence/GetEvidenceService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/evidence/GetEvidenceUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/evidence/GetEvidenceServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/architecture/RegularCodingRulesArchUnitTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/architecture/namingconvention/adapter/in/rest/RestControllerNamingConventionArchUnitTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/QuestionMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/QuestionnaireMother.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidence/EvidenceWithDetailsView.java
Labels: Ready to Review, P1

#132 FAC-493 Impl question answers history list service
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/answerhistory/GetAnswerHistoryListRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answerhistory/AnswerHistoryMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answerhistory/AnswerHistoryPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/user/UserMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AnswerHistory.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/FullUser.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/answerhistory/GetAnswerHistoryListUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/answerhistory/LoadAnswerHistoryListPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/answer/SubmitAnswerService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/answerhistory/GetAnswerHistoryListService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/answerhistory/GetAnswerHistoryListUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/answerhistory/GetAnswerHistoryListServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AnswerHistoryMother.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/answerhistory/AnswerHistoryJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/answerhistory/AnswerHistoryJpaRepository.java
Labels: Ready to Review, P1

#144 FAC-507 Change confidence level calculation algorithm
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AttributeValue.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/AssessmentResultTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/AttributeValueTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/SubjectValueTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/CalculateConfidenceServiceTest.java
Labels: Ready to Review, P2

#155 FAC-532:feature:Impl attribute question extract excel service
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/attribute/CreateAttributeValueExcelResponseDto.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/attribute/CreateAttributeValueExcelRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/calculate/AssessmentCalculateInfoLoadAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/calculate/ConfidenceLevelCalculateInfoLoadAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/minio/MinioAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/attributevalue/AttributeValueMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/attributevalue/AttributeValuePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/attribute/AttributeMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/Attribute.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/attribute/CreateAttributeValueExcelUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/attributevalue/LoadAttributeValuePort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/minio/UploadAttributeScoreExcelPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attribute/CreateAttributeValueExcelService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/attribute/CreateAttributeValueExcelUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/CreateAttributeValueExcelServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AttributeMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AttributeValueMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/QuestionMother.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/config/MinioBucketInitializer.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/config/MinioConfigProperties.java
  flickit-assessment-server/src/main/resources/application-dev.properties
  pom.xml
Labels: Ready to Review, P1

#154 FAC-529:fix:Prevent removing expert group owner kit access
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-common/src/main/resources/i18n/users/messages_en.properties
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/DeleteKitUserAccessService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/common/ErrorMessageKey.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/port/in/assessmentkit/DeleteKitUserAccessUseCaseParamTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/DeleteKitUserAccessServiceTest.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/spaceuseraccess/DeleteSpaceMemberService.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/common/ErrorMessageKey.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/spaceuseraccess/DeleteSpaceMemberServiceTest.java
Labels: Ready to Review, P3

#157 FAC-534: Generate ai report
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/AssessmentCommonAutoConfig.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/FileProperties.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/OpenAiProperties.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/util/TemplateEvaluator.java
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/attribute/CreateAssessmentAttributeAiReportRequestDto.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/attribute/CreateAssessmentAttributeAiReportResponseDto.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/attribute/CreateAssessmentAttributeAiReportRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/calculate/AssessmentCalculateInfoLoadAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/calculate/ConfidenceLevelCalculateInfoLoadAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/minio/MinioAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/openai/OpenAiAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/attributevalue/AttributeValueMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/attribute/AttributeMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/attribute/AttributePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/Attribute.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/attribute/CreateAssessmentAttributeAiReportUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/attribute/CreateAssessmentAttributeAiPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/attribute/LoadAttributePort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attribute/CreateAssessmentAttributeAiReportService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessment/CreateAssessmentAiReportUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/CreateAssessmentAttributeAiReportServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentResultMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AttributeMother.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
  flickit-assessment-server/src/main/resources/application-dev.properties
  pom.xml
Labels: Ready to Review, P2

#158 FAC-531:feature:Add description to maturity level
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/adapter/jpa/MaturityLevelJpaEntityMother.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/maturitylevel/MaturityLevelJpaEntity.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.26.xml
  flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/maturitylevel/MaturityLevelMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/maturitylevel/MaturityLevelPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/MaturityLevel.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/create/impl/MaturityLevelCreateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/MaturityLevelUpdateKitPersister.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/create/impl/MaturityLevelCreateKitPersisterTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/MaturityLevelUpdateKitPersisterTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/MaturityLevelMother.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/dsl/MaturityLevelDslModelMother.java
Labels: Ready to Review

#160 Fac 534 create ai report 2
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/FileProperties.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/openai/OpenAiAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/attribute/CreateAssessmentAttributeAiReportUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attribute/CreateAssessmentAttributeAiReportService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/CreateAssessmentAttributeAiReportServiceTest.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
Labels: Ready to Review

#161 FAC-546 Add questionnaire description to questionnaire list item
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/questionnaire/QuestionnaireMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/QuestionnaireListItem.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/questionnaire/GetAssessmentQuestionnaireListServiceTest.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/questionnaire/QuestionnaireJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/questionnaire/QuestionnaireListItemView.java
Labels: Ready to Review, P1

#163 FAC-544: Create attribute insight table
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/attributeinsight/AttributeInsightJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/attributeinsight/AttributeInsightJpaRepository.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.27.xml
  flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml
Labels: Ready to Review

#165 FAC-549 Add kit's 'about' to assessment report service output
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/report/LoadAssessmentReportInfoAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/report/AssessmentReportItem.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/ReportAssessmentServiceTest.java
Labels: Ready to Review
