Repository Flickit-Platform-Dev/flickit-assessment, pull requests merged in 2024-06, with the labels that each got.

#65 FAC-434 Add a List of kit maturity levels to the service output
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/report/LoadAssessmentReportInfoAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/report/AssessmentReportItem.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/ReportAssessmentServiceTest.java
Labels: Ready to Review

#63 FAC-431-fix-Don't save confidence level for empty answer
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/answer/SubmitAnswerService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/questionnaire/GetAssessmentQuestionnaireQuestionListService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/answer/SubmitAnswerServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/questionnaire/GetAssessmentQuestionnaireQuestionListServiceTest.java
Labels: Ready to Review

#58 FAC-401:feature:Grant assessment creator manager role
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/CreateAssessmentService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentuserrole/AssessmentPermissionCheckerService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/CreateAssessmentServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentuserrole/AssessmentPermissionCheckerServiceTest.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.21.xml
  flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml
Labels: Ready to Review

#64 FAC-432 Delete user assessment accesses when leaving space
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessment/AssessmentJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentuserrole/AssessmentUserRoleJpaRepository.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/out/persistence/assessmentuserrole/AssessmentUserRolePersistenceJpaAdapter.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/out/assessmentuserrole/DeleteSpaceAssessmentUserRolesPort.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/spaceuseraccess/DeleteSpaceMemberService.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/spaceuseraccess/LeaveSpaceService.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/spaceuseraccess/DeleteSpaceMemberServiceTest.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/spaceuseraccess/LeaveSpaceServiceTest.java
Labels: Ready to Review

#56 FAC-420 Rename quality attribute value
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/calculation/LoadAdviceCalculationInfoAdapter.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/persistence/attributevalue/AttributeValuePersistenceJpaAdapter.java
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/calculate/AssessmentCalculateInfoLoadAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/calculate/AssessmentCalculateResultPersistAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/calculate/ConfidenceLevelCalculateInfoLoadAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/attributevalue/AttributeValueMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/attributevalue/AttributeValuePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/constraint/AssessmentCoreDataConstraintErrorMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/attribute/AttributeMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/subject/SubjectMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/subject/SubjectPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/qualityattributevalue/QualityAttributeValueMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/report/LoadAssessmentReportInfoAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/report/LoadSubjectReportInfoAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/rest/qualityattribute/QualityAttributeDto.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentResult.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/Attribute.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AttributeValue.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/Subject.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/SubjectValue.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/ReportAssessmentUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentresult/LoadAssessmentReportInfoPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/attributevalue/CreateAttributeValuePort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/attributevalue/LoadAttributeValueListPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/qualityattributevalue/CreateQualityAttributeValuePort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/qualityattributevalue/LoadAttributeValueListPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/CalculateAssessmentService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/CalculateConfidenceService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/CreateAssessmentService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/adapter/out/calculate/AssessmentCalculateInfoLoadAdapterTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/adapter/out/rest/qualityattribute/QualityAttributeDtoTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/AssessmentResultTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/AttributeValueTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/SubjectValueTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/CalculateAssessmentServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/CalculateConfidenceServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/CreateAssessmentServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/subject/GetSubjectProgressServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/adapter/dto/AttributeDtoMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/adapter/jpa/AttributeValueJpaEntityMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/adapter/jpa/QuestionImpactEntityMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AttributeMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AttributeValueMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/SubjectMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/SubjectValueMother.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/attributevalue/AttributeValueJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/attributevalue/AttributeValueJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/attributevalue/SubjectRefNumAttributeValueView.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.21.xml
Labels: Ready to Review

#73 FAC-418:feature:Add manageable to new assessment list service
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentListItem.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessment/LoadAssessmentListPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetSpaceAssessmentListService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetSpaceAssessmentListServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentMother.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessment/AssessmentJoinResultView.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessment/AssessmentJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessment/UserAssessmentListItemView.java
Labels: Ready to Review

#39 FAC-391-editing-expert-group-picture
  flickit-assessment-common/src/main/resources/i18n/users/messages_en.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/expertgroup/ExpertGroupJpaRepository.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/expertgroup/CreateExpertGroupRestController.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/expertgroup/UpdateExpertGroupPictureResponseDto.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/expertgroup/UpdateExpertGroupPictureRestController.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/out/minio/MinioAdapter.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/out/persistence/expertgroup/ExpertGroupPersistenceJpaAdapter.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/expertgroup/UpdateExpertGroupPictureUseCase.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/out/expertgroup/UpdateExpertGroupPicturePort.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/out/minio/DeleteFilePort.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/expertgroup/UpdateExpertGroupPictureService.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/common/ErrorMessageKey.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/port/in/expertgroup/UpdateExpertGroupPictureUseCaseParamTest.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/expertgroup/UpdateExpertGroupPictureServiceTest.java
  flickit-assessment-users/src/test/resources/postman/flickit-assessment-users.postman_collection.json
Labels: Ready to Merge

#67 FAC-433:feature:Change primary key of fak tables
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/adapter/out/calculate/AssessmentCalculateInfoLoadAdapterTest.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/asnweroptionimpact/AnswerOptionImpactJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/levelcompetence/LevelCompetenceJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/questionimpact/QuestionImpactJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/questionnaire/QuestionnaireJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/subjectquestionnaire/SubjectQuestionnaireJpaEntity.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.21.xml
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answeroptionimpact/AnswerOptionImpactMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/levelcompetence/LevelCompetencePersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/questionimpact/QuestionImpactMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/subjectquestionnaire/SubjectQuestionnaireMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/subjectquestionnaire/SubjectQuestionnairePersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/QuestionImpact.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/answeroptionimpact/CreateAnswerOptionImpactPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/levelcomptenece/CreateLevelCompetencePort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/subjectquestionnaire/CreateSubjectQuestionnairePort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/create/impl/MaturityLevelCreateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/create/impl/QuestionCreateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/create/impl/SubjectQuestionnaireCreateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/MaturityLevelUpdateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/QuestionUpdateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/SubjectQuestionnaireUpdateKitPersister.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/create/impl/MaturityLevelCreateKitPersisterTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/create/impl/QuestionCreateKitPersisterTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/create/impl/SubjectQuestionnaireCreateKitPersisterTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/MaturityLevelUpdateKitPersisterTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/SubjectQuestionnaireUpdateKitPersisterTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/QuestionImpactMother.java
Labels: Ready to Review

#69 Fac 435 impl add kit version id to kit subject repository methods
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/calculate/AssessmentCalculateResultPersistAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/questionnaire/QuestionnairePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/subjectvalue/SubjectValueMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/subjectvalue/SubjectValuePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/report/LoadAssessmentReportInfoAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/report/LoadSubjectReportInfoAdapter.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/adapter/jpa/SubjectValueJpaEntityMother.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/attributevalue/AttributeValueJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/attributevalue/SubjectIdAttributeValueView.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/subjectvalue/SubjectValueJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/subjectvalue/SubjectValueJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/assessmentkit/AssessmentKitJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/questionnaire/QuestionnaireJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/subject/SubjectJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/assessmentkit/AssessmentKitPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/questionnaire/QuestionnairePersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/subject/SubjectPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/assessmentkit/LoadActiveKitVersionIdPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/questionnaire/LoadKitQuestionnaireDetailPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/subject/LoadSubjectPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/subject/UpdateSubjectPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/SubjectUpdateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/questionnaire/GetKitQuestionnaireDetailService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/subject/GetKitSubjectDetailService.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/SubjectUpdateKitPersisterTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/questionnaire/GetKitQuestionnaireDetailServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/subject/GetKitSubjectDetailServiceTest.java
Labels: Ready to Review

#72 Fac 436 impl add kit version id to kit subject adapter methods
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/calculate/AssessmentCalculateInfoLoadAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/calculate/ConfidenceLevelCalculateInfoLoadAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/attributevalue/AttributeValuePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/subject/SubjectPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/subjectvalue/SubjectValueMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/subjectvalue/SubjectValuePersistenceJpaAdapter.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/adapter/out/calculate/AssessmentCalculateInfoLoadAdapterTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/adapter/jpa/AttributeJapEntityMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/adapter/jpa/SubjectJpaEntityMother.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessment/AssessmentJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/attributevalue/AttributeValueJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/AttributeJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/AttributeJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/subject/SubjectJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/subject/SubjectJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/attribute/AttributeMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/attribute/AttributePersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/subject/SubjectMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/subject/SubjectPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/subject/LoadSubjectsPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitDetailService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitStatsService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetPublishedKitService.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitDetailServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitStatsServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/GetPublishedKitServiceTest.java
Labels: Ready to Review

#76 FAC-419:feature:Remove GetAnswerListUseCase service
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/answer/GetAnswerListRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answer/AnswerMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answer/AnswerPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/answer/GetAnswerListUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/answer/LoadAnswerListPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/answer/GetAnswerListService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/answer/GetAnswerListServiceTest.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/answer/AnswerJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/questionnaire/QuestionnaireJpaRepository.java
Labels: Ready to Review

#75 FAC-427:feature:Remove CountAssessments service
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/CountAssessmentsResponseDto.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/CountAssessmentsRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/CountAssessmentsUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessment/CountAssessmentsPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/CountAssessmentsService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessment/CountAssessmentsUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/CountAssessmentsServiceTest.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
Labels: Ready to Review

#77 FAC-402:feature:Remove GetQuestionnairesProgressUseCase service
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/questionnaire/GetQuestionnairesProgressResponseDto.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/questionnaire/GetQuestionnairesProgressRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answer/AnswerPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/questionnaire/GetQuestionnairesProgressUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/questionnaire/GetQuestionnairesProgressPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/questionnaire/GetQuestionnairesProgressService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/questionnaire/GetQuestionnairesProgressServiceTest.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/answer/AnswerJpaRepository.java
Labels: Ready to Review

#79 FAC-444:feature:Add kit version id to kit questionnaire adapter methods
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/rest/answeroption/AnswerOptionDto.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/questionnaire/QuestionnaireJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/questionnaire/QuestionnaireJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/questionnaire/QuestionnaireMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/questionnaire/QuestionnairePersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/questionnaire/UpdateQuestionnairePort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/QuestionnaireUpdateKitPersister.java
Labels: Ready to Review

#74 Fac 440 impl add kit version id to maturity level persistence jpa adapter
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/calculation/LoadAdviceCalculationInfoAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/maturitylevel/MaturityLevelPersistenceJpaAdapter.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/adapter/jpa/MaturityLevelJpaEntityMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/adapter/jpa/QuestionImpactEntityMother.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/AttributeJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/AttributeJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/levelcompetence/LevelCompetenceJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/levelcompetence/LevelCompetenceJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/maturitylevel/MaturityLevelJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/maturitylevel/MaturityLevelJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/questionimpact/QuestionImpactJpaEntity.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/levelcompetence/LevelCompetencePersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/levelcompetence/MaturityLevelCompetenceMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/maturitylevel/MaturityLevelMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/maturitylevel/MaturityLevelPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/question/QuestionPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/questionimpact/QuestionImpactPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/maturitylevel/DeleteMaturityLevelPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/maturitylevel/LoadAttributeMaturityLevelsPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/maturitylevel/LoadMaturityLevelsPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/maturitylevel/UpdateMaturityLevelPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/question/LoadAttributeLevelQuestionsPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitDetailService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/GetPublishedKitService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/MaturityLevelUpdateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/attribute/GetKitAttributeDetailService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/attribute/GetKitKitAttributeLevelQuestionsDetailService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/question/GetKitQuestionDetailService.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/GetKitDetailServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/GetPublishedKitServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/MaturityLevelUpdateKitPersisterTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/attribute/GetKitAttributeDetailServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/attribute/GetKitAttributeLevelQuestionsDetailServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/question/GetKitQuestionDetailServiceTest.java
Labels: Ready to Merge

#80 Fac 443 impl add kit version id to level competence persistence jpa adapter
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/levelcompetence/LevelCompetenceJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/maturitylevel/MaturityLevelJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/levelcompetence/LevelCompetencePersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/levelcomptenece/DeleteLevelCompetencePort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/levelcomptenece/UpdateLevelCompetencePort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/MaturityLevelUpdateKitPersister.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/MaturityLevelUpdateKitPersisterTest.java
Labels: Ready to Review

#78 FAC-441 Refactor attribute persistence jpa adapter methods due to new composite pk
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/persistence/attributevalue/AttributeValuePersistenceJpaAdapter.java
  flickit-assessment-common/src/main/resources/i18n/kit/messages_en.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/calculate/AssessmentCalculateInfoLoadAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/calculate/ConfidenceLevelCalculateInfoLoadAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/attributevalue/AttributeValueMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/attributevalue/AttributeValuePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/attribute/AttributePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/subject/SubjectPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/report/LoadAssessmentReportInfoAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/report/LoadSubjectReportInfoAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/attributevalue/LoadAttributeValueListPort.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/adapter/out/calculate/AssessmentCalculateInfoLoadAdapterTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/adapter/jpa/AttributeJapEntityMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/adapter/jpa/AttributeValueJpaEntityMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/adapter/jpa/SubjectJpaEntityMother.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessment/AssessmentJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/attributevalue/AttributeValueJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/attributevalue/AttributeValueJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/AttributeJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/AttributeJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/question/QuestionJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/subject/SubjectJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/subject/SubjectJpaRepository.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.21.xml
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/attribute/AttributeMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/attribute/AttributePersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/subject/SubjectMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/subject/SubjectPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/updatekitbydsl/LoadAssessmentKitFullInfoAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/attribute/CountAttributeImpactfulQuestionsPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/attribute/LoadAllAttributesPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/attribute/LoadAttributePort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/attribute/UpdateAttributePort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/AttributeUpdateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/attribute/GetKitAttributeDetailService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/question/GetKitQuestionDetailService.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/attribute/GetKitAttributeDetailServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/question/GetKitQuestionDetailServiceTest.java
Labels: Ready to Review

#82 Fac 447 AddKitVersionId to answerOption usecase
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/calculate/AssessmentCalculateInfoLoadAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answer/AnswerPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/question/QuestionPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/answer/UpdateAnswerPort.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/adapter/out/calculate/AssessmentCalculateInfoLoadAdapterTest.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/answeroption/AnswerOptionJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/answeroption/AnswerOptionJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answeroption/AnswerOptionMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answeroption/AnswerOptionPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/answeroption/UpdateAnswerOptionPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/QuestionUpdateKitPersister.java
Labels: Ready to Review

#83 FAC-454: refactor : remove extra query from SubjectQuestionnaireJpaRe…
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/subjectquestionnaire/SubjectQuestionnaireJpaRepository.java
Labels: Ready to Review

#85 FAC-450: add owner display name to list spaces
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/space/SpaceJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/space/SpaceWithDetails.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/out/persistence/space/SpacePersistenceJpaAdapter.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/space/GetSpaceListUseCase.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/out/space/LoadSpaceListPort.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/space/GetSpaceListService.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/space/GetSpaceListServiceTest.java
Labels: Ready to Review

#86 FAC-455 Fix usage of partial of composite key in query
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/assessmentkit/AssessmentKitJpaRepository.java
Labels: Ready to Review

#89 FAC-457: Bug remove website field obligation from update expert group
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/expertgroup/CreateExpertGroupRestController.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/expertgroup/UpdateExpertGroupRestController.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/expertgroup/CreateExpertGroupUseCase.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/expertgroup/UpdateExpertGroupUseCase.java
Labels: Ready to Review

#90 FAC-446:feature:Add kit version id to kit question adapter methods
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/calculation/LoadCreatedAdviceDetailsAdapter.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/persistence/assessment/AssessmentPersistenceJpaAdapter.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/out/assessment/LoadAssessmentKitVersionIdPort.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/port/out/calculation/LoadCreatedAdviceDetailsPort.java
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/application/service/advice/CreateAdviceService.java
  flickit-advice-engine/src/test/java/org/flickit/assessment/advice/application/service/advice/CreateAdviceServiceTest.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answer/AnswerPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/evidence/EvidencePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/question/QuestionPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/question/LoadQuestionMayNotBeApplicablePort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/question/LoadQuestionnaireQuestionListPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/question/LoadQuestionsBySubjectPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/answer/SubmitAnswerService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/questionnaire/GetAssessmentQuestionnaireQuestionListService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/subject/GetSubjectProgressService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/answer/SubmitAnswerServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/questionnaire/GetAssessmentQuestionnaireQuestionListServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/subject/GetSubjectProgressServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/adapter/jpa/QuestionJpaEntityMother.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/answeroption/AnswerOptionJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/question/QuestionJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/question/QuestionJpaRepository.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answeroption/AnswerOptionPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/question/QuestionMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/question/QuestionPersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/questionnaire/QuestionnairePersistenceJpaAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/updatekitbydsl/LoadAssessmentKitFullInfoAdapter.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/answeroption/LoadAnswerOptionsByQuestionPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/question/LoadQuestionPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/question/UpdateQuestionPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/port/out/subject/CountSubjectQuestionsPort.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/QuestionUpdateKitPersister.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/question/GetKitQuestionDetailService.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/subject/GetKitSubjectDetailService.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/QuestionUpdateKitPersisterTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/question/GetKitQuestionDetailServiceTest.java
  flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/subject/GetKitSubjectDetailServiceTest.java
Labels: Ready to Review

#97 FAC-467: Fix bug where spaces without assessments do not load
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/space/SpaceJpaRepository.java
Labels: Ready to Review

#92 FAC-465:feature:Add kitVersionId to core QuestionPersistenceJpaAdapter.loadByQuestionnaireId
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/question/QuestionPersistenceJpaAdapter.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/questionnaire/GetAssessmentQuestionnaireQuestionListServiceTest.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/answeroption/AnswerOptionJpaRepository.java
Labels: Ready to Review

#95 FAC-466:feature:Add kitVersionId to AnswerOptionImpactJpaRepository.findAllByOptionIdInAndKitVersionId
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/calculate/AssessmentCalculateInfoLoadAdapter.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/adapter/out/calculate/AssessmentCalculateInfoLoadAdapterTest.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/asnweroptionimpact/AnswerOptionImpactJpaRepository.java
Labels: Ready to Review

#91 FAC-458:feature:Sort GetAssessmentUsersUseCase result by displayName
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentuserrole/AssessmentUserRolePersistenceJpaAdapter.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentuserrole/AssessmentUserRoleJpaRepository.java
Labels: question

#93 FAC-461:feature:Add kitVersionId to EvidenceJpaRepository.findAssessentAttributeEvidencesByTypeOrderByLastModificationTimeDesc
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidence/EvidenceJpaRepository.java
Labels: question

#61 Fac 428 feature impl delete space invitation
  flickit-assessment-common/src/main/resources/i18n/users/messages_en.properties
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/spaceinvitee/SpaceInviteeJpaRepository.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/spaceinvitee/DeleteSpaceInvitationRestController.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/out/persistence/spaceinvitee/SpaceInviteePersistenceJpaAdapter.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/spaceinvitee/DeleteSpaceInvitationUseCase.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/out/spaceinvitee/DeleteSpaceInvitationPort.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/out/spaceinvitee/LoadSpaceInvitationPort.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/spaceinvitee/DeleteSpaceInvitationService.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/common/ErrorMessageKey.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/port/in/spaceinvitee/DeleteSpaceInvitationUseCaseParamTest.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/spaceinvitee/DeleteSpaceInvitationServiceTest.java
  flickit-assessment-users/src/test/resources/postman/flickit-assessment-users.postman_collection.json
Labels: Ready to Review

#99 FAC-449:feature:Add space and manageable to assessment report item
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/report/LoadAssessmentReportInfoAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/report/AssessmentReportItem.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/ReportAssessmentUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentresult/LoadAssessmentReportInfoPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/ReportAssessmentService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/ReportAssessmentServiceTest.java
Labels: Ready to Review

#105 FAC-477 Rename old sequence names
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.14.xml
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.17.xml
Labels: Ready to Review

#68 FAC-409: file type size limitation
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/FileProperties.java
  flickit-assessment-common/src/main/java/org/flickit/assessment/common/error/ErrorMessageKey.java
  flickit-assessment-common/src/main/resources/i18n/messages_en.properties
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/expertgroup/CreateExpertGroupService.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/expertgroup/UpdateExpertGroupPictureService.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/expertgroup/CreateExpertGroupServiceTest.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/expertgroup/UpdateExpertGroupPictureServiceTest.java
Labels: Ready to Review

#100 FAC-468:feature:Add Assessor's Assistant role
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentuserrole/GetAssessmentUserRolesService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/AssessmentUserRoleTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentuserrole/GetAssessmentUserRolesServiceTest.java
Labels: Ready to Merge

#101 FAC-469 Make assessment list item maturity level null
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetSpaceAssessmentListService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetSpaceAssessmentListServiceTest.java
Labels: Ready to Review

#44 FAC-404-remove-export-group-picture
  flickit-assessment-common/src/main/resources/i18n/users/messages_en.properties
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/expertgroup/DeleteExpertGroupPictureRestController.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/out/minio/MinioAdapter.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/expertgroup/DeleteExpertGroupPictureUseCase.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/expertgroup/DeleteExpertGroupPictureService.java
  flickit-assessment-users/src/main/java/org/flickit/assessment/users/common/ErrorMessageKey.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/port/in/expertgroup/DeleteExpertGroupPictureUseCaseParamTest.java
  flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/expertgroup/DeleteExpertGroupPictureServiceTest.java
  flickit-assessment-users/src/test/resources/postman/flickit-assessment-users.postman_collection.json
Labels: In Progress

#115 FAC-485:feature:Add viewable to AssessmentListItem
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentListItem.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetSpaceAssessmentListService.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetSpaceAssessmentListServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentMother.java
Labels: Ready to Review

#116 FAC-486:feature:Add editable to GetAssessmentUsersUseCase.Assessment user
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentuserrole/AssessmentUserRolePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/space/SpacePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentuserrole/GetAssessmentUsersUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessmentuserrole/LoadAssessmentUsersPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/space/LoadSpaceOwnerPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/CreateAssessmentService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentuserrole/AssessmentPermissionCheckerService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentuserrole/DeleteUserAssessmentRoleService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentuserrole/GetAssessmentUsersService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentuserrole/UpdateUserAssessmentRoleService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/CreateAssessmentServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentuserrole/AssessmentPermissionCheckerServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentuserrole/DeleteUserAssessmentRoleServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentuserrole/GetAssessmentUsersServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentuserrole/UpdateUserAssessmentRoleServiceTest.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentuserrole/AssessmentUserRoleJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentuserrole/AssessmentUserView.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/space/SpaceJpaRepository.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.22.xml
  flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml
  flickit-assessment-server/src/main/resources/application-dev.properties
Labels: Ready to Review

#94 FAC-459: Remove ref num
  flickit-advice-engine/src/main/java/org/flickit/assessment/advice/adapter/out/calculation/LoadAdviceCalculationInfoAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answer/AnswerMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answer/AnswerPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/attributevalue/AttributeValueMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/attributevalue/AttributeValuePersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/evidence/EvidenceMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/evidence/EvidencePersistenceJpaAdapter.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/adapter/out/calculate/AssessmentCalculateInfoLoadAdapterTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/adapter/jpa/AnswerJpaEntityMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/adapter/jpa/AttributeValueJpaEntityMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/adapter/jpa/MaturityLevelJpaEntityMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/adapter/jpa/QuestionJpaEntityMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/adapter/jpa/SubjectJpaEntityMother.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/answer/AnswerJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/attributevalue/AttributeValueJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/attributevalue/AttributeValueJpaRepository.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidence/EvidenceJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/answeroption/AnswerOptionJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/AttributeJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/maturitylevel/MaturityLevelJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/question/QuestionJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/questionnaire/QuestionnaireJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/subject/SubjectJpaEntity.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.23.xml
  flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/answeroption/AnswerOptionMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/attribute/AttributeMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/maturitylevel/MaturityLevelMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/question/QuestionMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/questionnaire/QuestionnaireMapper.java
  flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/subject/SubjectMapper.java
Labels: Ready to Review

#102 FAC-473: Create table and JPA entity for evidence_attachment table
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidenceattachment/EvidenceAttachmentJpaEntity.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.23.xml
Labels: Ready to Review

#88 FAC-445: Remove assessment color
  flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/CreateAssessmentRequestDto.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/CreateAssessmentRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/UpdateAssessmentRequestDto.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/UpdateAssessmentRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentcolor/GetAssessmentColorsResponseDto.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessmentcolor/GetAssessmentColorsRestController.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentMapper.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentPersistenceJpaAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/report/LoadAssessmentReportInfoAdapter.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/Assessment.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentColor.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentListItem.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/report/AssessmentReportItem.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/CreateAssessmentUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/GetAssessmentColorsUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/UpdateAssessmentUseCase.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessment/CreateAssessmentPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessment/UpdateAssessmentPort.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/CreateAssessmentService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetSpaceAssessmentListService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/UpdateAssessmentService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentcolor/GetAssessmentColorsService.java
  flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/AssessmentColorTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessment/CreateAssessmentUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessment/UpdateAssessmentUseCaseParamTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/CreateAssessmentServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/ReportAssessmentServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/UpdateAssessmentServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentcolor/GetAssessmentColorsServiceTest.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/architecture/constants/ArchUnitTestConstants.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/adapter/jpa/AssessmentJpaEntityMother.java
  flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentMother.java
  flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessment/AssessmentJpaEntity.java
  flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessment/AssessmentJpaRepository.java
  flickit-assessment-data/src/main/resources/liquibase/changelog-0.23.xml
Labels: Ready to Review
